version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8004-8007:8004-8007
    restart: always

  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server
    stdin_open: true
    tty: true
    restart: always
